#require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
=begin
RSpec.describe Api::V1::BussinesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Bussine. As you add validations to Bussine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BussinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bussines as @bussines" do
      bussine = Bussine.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:bussines)).to eq([bussine])
    end
  end

  describe "GET #show" do
    it "assigns the requested bussine as @bussine" do
      bussine = Bussine.create! valid_attributes
      get :show, params: {id: bussine.to_param}, session: valid_session
      expect(assigns(:bussine)).to eq(bussine)
    end
  end

  describe "GET #new" do
    it "assigns a new bussine as @bussine" do
      get :new, params: {}, session: valid_session
      expect(assigns(:bussine)).to be_a_new(Bussine)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bussine as @bussine" do
      bussine = Bussine.create! valid_attributes
      get :edit, params: {id: bussine.to_param}, session: valid_session
      expect(assigns(:bussine)).to eq(bussine)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Bussine" do
        expect {
          post :create, params: {bussine: valid_attributes}, session: valid_session
        }.to change(Bussine, :count).by(1)
      end

      it "assigns a newly created bussine as @bussine" do
        post :create, params: {bussine: valid_attributes}, session: valid_session
        expect(assigns(:bussine)).to be_a(Bussine)
        expect(assigns(:bussine)).to be_persisted
      end

      it "redirects to the created bussine" do
        post :create, params: {bussine: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Bussine.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bussine as @bussine" do
        post :create, params: {bussine: invalid_attributes}, session: valid_session
        expect(assigns(:bussine)).to be_a_new(Bussine)
      end

      it "re-renders the 'new' template" do
        post :create, params: {bussine: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bussine" do
        bussine = Bussine.create! valid_attributes
        put :update, params: {id: bussine.to_param, bussine: new_attributes}, session: valid_session
        bussine.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bussine as @bussine" do
        bussine = Bussine.create! valid_attributes
        put :update, params: {id: bussine.to_param, bussine: valid_attributes}, session: valid_session
        expect(assigns(:bussine)).to eq(bussine)
      end

      it "redirects to the bussine" do
        bussine = Bussine.create! valid_attributes
        put :update, params: {id: bussine.to_param, bussine: valid_attributes}, session: valid_session
        expect(response).to redirect_to(bussine)
      end
    end

    context "with invalid params" do
      it "assigns the bussine as @bussine" do
        bussine = Bussine.create! valid_attributes
        put :update, params: {id: bussine.to_param, bussine: invalid_attributes}, session: valid_session
        expect(assigns(:bussine)).to eq(bussine)
      end

      it "re-renders the 'edit' template" do
        bussine = Bussine.create! valid_attributes
        put :update, params: {id: bussine.to_param, bussine: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bussine" do
      bussine = Bussine.create! valid_attributes
      expect {
        delete :destroy, params: {id: bussine.to_param}, session: valid_session
      }.to change(Bussine, :count).by(-1)
    end

    it "redirects to the bussines list" do
      bussine = Bussine.create! valid_attributes
      delete :destroy, params: {id: bussine.to_param}, session: valid_session
      expect(response).to redirect_to(bussines_url)
    end
  end

end
=end